print('This is example of String:', 'Hello with single quotes')
print('This is example of String:', "Hello with double quotes")
print('This is example of String:', """Hello with triple quotes""")
print('This is example of decimal 45:', 45)
print('This is example of octal 0o477:', 0o477)
print('This is example of hexadecimal 0x477adc:', 0x477adc)
print('This is example of float', 1.556)
print('This is example of exponential 1.6e3', 1.6e3)
print('This is example of boolean', True)
